/**
 * config.js — AUTO-GENERATED by scripts/write-dev-config.sh. Do not
 * edit by hand — it gets overwritten every time dev-up.sh runs.
 */
export const API_BASE_URL = 'http://172.25.175.170:8080';
export const BONUS_GAME_URL = 'http://172.25.175.170:3000';
