#!/usr/bin/env bash
# write-dev-config.sh
# -----------------------------------------------------------------------
# Detects this WSL2 instance's current IP (localhost forwarding is
# broken in this dev environment, so the frontends have to address the
# backend by IP instead) and writes it into the two generated config.js
# files both frontends import from. Run this once per session, before
# starting any of the three servers — dev-up.sh does this for you
# automatically, so you normally don't need to run this file directly.
# -----------------------------------------------------------------------
set -euo pipefail

# Resolve the repo root as "the directory this script's parent lives
# in", so this works no matter what directory you invoke it from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

IP="$(ip addr show eth0 | grep -oP 'inet \K[\d.]+' | head -n1)"

if [ -z "$IP" ]; then
  echo "write-dev-config: could not detect an IP on eth0 — is this actually running inside WSL2?" >&2
  exit 1
fi

echo "write-dev-config: detected WSL IP: $IP"

RPG_CONFIG="$REPO_ROOT/rpg-frontend/src/config.js"
RESUME_CONFIG="$REPO_ROOT/resume-frontend/easter-egg/config.js"

cat > "$RPG_CONFIG" <<EOF
/**
 * config.js — AUTO-GENERATED by scripts/write-dev-config.sh. Do not
 * edit by hand — it gets overwritten every time dev-up.sh runs.
 *
 * If localhost:8080 ever starts working again in this environment
 * (WSL2 localhost forwarding fixed), this whole generator setup can
 * be retired in favor of a hardcoded 'http://localhost:8080'.
 */
export const API_BASE_URL = 'http://${IP}:8080';
EOF

cat > "$RESUME_CONFIG" <<EOF
/**
 * config.js — AUTO-GENERATED by scripts/write-dev-config.sh. Do not
 * edit by hand — it gets overwritten every time dev-up.sh runs.
 */
export const API_BASE_URL = 'http://${IP}:8080';
export const BONUS_GAME_URL = 'http://${IP}:3000';
EOF

echo "write-dev-config: wrote $RPG_CONFIG"
echo "write-dev-config: wrote $RESUME_CONFIG"

# Exported so dev-up.sh (which sources this script) can use it when
# building ALLOWED_ORIGINS, without re-detecting the IP a second time.
export DEV_IP="$IP"
