/**
 * config.js — AUTO-GENERATED by scripts/write-dev-config.sh. Do not
 * edit by hand — it gets overwritten every time dev-up.sh runs.
 *
 * If localhost:8080 ever starts working again in this environment
 * (WSL2 localhost forwarding fixed), this whole generator setup can
 * be retired in favor of a hardcoded 'http://localhost:8080'.
 */
export const API_BASE_URL = 'http://172.25.175.170:8080';
